Projet/Models/ShoppingCart/ShoppingCart.cs
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Projet.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Projet.Models.ShoppingCart
{
    public class ShoppingCart
    {
        private readonly ApplicationDbContext _dbContext;

        public ShoppingCart(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        
        public string ShoppingCartId { get; set; }

        public List<ShoppingCartItem> ShoppingCartItems { get; set; }

        public static ShoppingCart GetCart(IServiceProvider services)
        {

            ISession session = services.GetRequiredService<IHttpContextAccessor>()?.HttpContext.Session;

            var context = services.GetService<ApplicationDbContext>();
            string cartId = session.GetString("CartId") ?? Guid.NewGuid().ToString();
            session.SetString("CartId", cartId);

            return new ShoppingCart(context) { ShoppingCartId = cartId };
        } // GetCart

        public void AddToCart(Produit produit, int quantity)
        {

            var shoppingCartItem = _dbContext.cartItems.SingleOrDefault(i => i.Produit.ProduitId == produit.ProduitId && i.ShoppingCartId == ShoppingCartId);

            if (shoppingCartItem == null)
            {
                shoppingCartItem = new ShoppingCartItem()
                {
                    ShoppingCartId = ShoppingCartId,
                    Produit = produit,
                    Amount = 1,
                    CartStatus = true,
                    DateAjout = DateTime.Now

                };

                _dbContext.cartItems.Add(shoppingCartItem);
            }
            else
            {

                shoppingCartItem.Amount++;

            }

            _dbContext.SaveChanges();

        } // Add To Cart

        public int RemoveFromCart(Produit produit)
        {

            var shoppingCartItem = _dbContext.cartItems.SingleOrDefault(i => i.Produit.ProduitId == produit.ProduitId && i.ShoppingCartId == ShoppingCartId);
            var quantity = 0;

            if (shoppingCartItem != null)
            {

                if (shoppingCartItem.Amount > 1)
                {
                    shoppingCartItem.Amount--;
                    quantity = shoppingCartItem.Amount;
                    
                }
                else
                {
                    _dbContext.cartItems.Remove(shoppingCartItem);
                }

            }

            _dbContext.SaveChanges();
            return quantity;
        } // Remove from Cart

        public List<ShoppingCartItem> GetCartItems()
        {
            var ShoppingCartItems = _dbContext.cartItems.Where(i => i.ShoppingCartId == ShoppingCartId).Include(i => i.Produit).ToList();
            return ShoppingCartItems;

        } // Get Cart Items

        public void ClearCart()
        {
            var cartItems = _dbContext.cartItems.Where(c => c.ShoppingCartId == ShoppingCartId);
            _dbContext.cartItems.RemoveRange(cartItems);
            _dbContext.SaveChanges();
        } // Clear cart

        public decimal GetShoppingCartTotal()
        {

            var total = _dbContext.cartItems.Select(c => c.Produit.AskedPrice * c.Amount).Sum();
            return total;
        } // Total


        public int CreateOrder(Order order)
        {
            decimal orderTotal = 0;

            var cartItems = GetCartItems();
            // Iterate over the items in the cart, 
            // adding the order details for each
            foreach (var item in cartItems)
            {
                var orderDetail = new OrderDetail
                {
                    ProduitId = item.ShoppingCartItemID,
                    OrderId = order.OrderId,
                    UnitPrice = item.Produit.AskedPrice,
                    Quantity = item.Amount
                };
                // Set the order total of the shopping cart
                orderTotal += (item.Amount * item.Produit.AskedPrice);

                _dbContext.orderDetails.Add(orderDetail);

            }
            // Set the order's total to the orderTotal count
            order.OrderTotal = orderTotal;

            // Save the order
            _dbContext.SaveChanges();
            // Empty the shopping cart
            ClearCart();
            // Return the OrderId as the confirmation number
            return order.OrderId;
        }


    }// Class
}

Projet/ViewModels/ShoppingCartViewModel.cs
using Projet.Models.ShoppingCart;
using System;

namespace Projet.ViewModels
{
    public class ShoppingCartViewModel
    {
        public ShoppingCart ShoppingCart;
        public Decimal shoppingCartTotal;
    }
    
}

Projet/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Projet.Models;
using Projet.Models.ShoppingCart;
using Projet.Interfaces;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using Projet.ViewModels;
using System;
using System.Linq;

namespace Projet.Controllers
{
    public class OrderController : Controller

    {
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrderRepository _orderRepository;

        public OrderController(ShoppingCart shoppingCart, IOrderRepository orderRepository)
        {
            _shoppingCart = shoppingCart;
            _orderRepository = orderRepository;
        }

        [HttpGet]
        public IActionResult CheckOut()
        {

            List<SelectListItem> provinces = new List<SelectListItem>
                  {
                     new SelectListItem { Value = "TO", Text="Toronto" },
                     new SelectListItem { Value = "QC", Text="Quebec" },
                     new SelectListItem { Value = "NB", Text="Nouveau Brunswick" }

                   };

            ViewBag.provinces = provinces;

            List<SelectListItem> countries = new List<SelectListItem>
                  {
                     new SelectListItem { Value = "Canada", Text="Canada" }

                   };

            ViewBag.countries = countries;


            List<SelectListItem> payements = new List<SelectListItem>
                  {
                     new SelectListItem { Value = "VISA", Text="VISA" },
                     new SelectListItem { Value = "Master Card", Text="Master Card" },
                     new SelectListItem { Value = "Amex", Text="Amex" }

                   };

            ViewBag.payements = payements;
            return View();
        }


        [HttpPost]
        public IActionResult CheckOut(OrderViewModel orderVM)
        {
           
            var items = _shoppingCart.GetCartItems();
            _shoppingCart.ShoppingCartItems = items;

            if (_shoppingCart.ShoppingCartItems.Count == 0)
            {

                ModelState.AddModelError("", "Your cart is empty, add some product first!");

            }

            if (ModelState.IsValid)
            {
                var order = new Order()
                {

                    Address = orderVM.Address,
                    OrderDate = DateTime.Now,
                    Email = orderVM.Email,
                    Payement = orderVM.Payement,
                    City = orderVM.City,
                    Country = orderVM.Country,
                    FirstName = orderVM.FirstName,
                    LastName = orderVM.LastName,
                    Username = User.Identity.Name,
                    PhoneNumber = orderVM.PhoneNumber,
                    Province = orderVM.Province,
                    PostalCode = orderVM.PostalCode


                };
                //_orderRepository.CreateOrder(order);
                // _shoppingCart.ClearCart();

                //Save Order
                _orderRepository.getContext().orders.Add(order);
                _orderRepository.getContext().SaveChanges();
                //Process the order
                //var cart = ShoppingCart.GetCart(_);
                _shoppingCart.CreateOrder(order);




                return RedirectToAction("CheckOutComplete", new { id = order.OrderId });
            }

            List<SelectListItem> provinces = new List<SelectListItem>
                  {
                     new SelectListItem { Value = "TORONTO", Text="Toronto" },
                     new SelectListItem { Value = "Quebec", Text="Quebec" },
                     new SelectListItem { Value = "Nouveau Brunswick", Text="Nouveau Brunswick" }

                   };

            ViewBag.provinces = provinces;

            List<SelectListItem> countries = new List<SelectListItem>
                  {
                     new SelectListItem { Value = "CANADA", Text="Canada" }

                   };

            ViewBag.countries = countries;


            List<SelectListItem> payements = new List<SelectListItem>
                  {
                     new SelectListItem { Value = "VISA", Text="VISA" },
                     new SelectListItem { Value = "Master Card", Text="Master Card" },
                     new SelectListItem { Value = "AmeX", Text="Amex" }

                   };

            ViewBag.payements = payements;


            return View(orderVM);
        }

        public IActionResult CheckOutComplete(int id)
        {

            // Validate customer owns this order
            bool isValid = _orderRepository.getContext().orders.Any(
                o => o.OrderId == id &&
                o.Username == User.Identity.Name);

            if (isValid)
            {
                return View(id);
            }
            else
            {
                return View("ErrorOnCommand");
            }
        }
    }
}

Projet/Controllers/ShoppingCartController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Projet.Data.Interfaces;
using Projet.ViewModels;
using Projet.Models.ShoppingCart;

namespace Projet.Controllers
{
    public class ShoppingCartController : Controller
    { 
        private readonly IProduitRepository _produitRepository;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(IProduitRepository produitRepository, ShoppingCart shoppingCart)
        {
            _produitRepository = produitRepository;
            _shoppingCart = shoppingCart;
        }

        public ViewResult Index()
        {
            var items = _shoppingCart.GetCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var vm = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                shoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(vm);
        }
        public IActionResult AddToShoppingCart(int produitId)
        {
            var selectProd = _produitRepository.Produits.FirstOrDefault(p => p.ProduitId ==produitId);
            if (selectProd !=null)
            {
                _shoppingCart.AddToCart(selectProd, 1);
            }
            return RedirectToAction("Index");
        }

        public IActionResult RemoveFromShoppingCart(int produitId)
        {
            var selectProd = _produitRepository.Produits.FirstOrDefault(p => p.ProduitId == produitId);
            if (selectProd != null)
            {
                _shoppingCart.RemoveFromCart(selectProd);
            }
            return RedirectToAction("Index");
        }
    }
}

Projet/Views/ShoppingCart/Index.cshtml
@model ShoppingCartViewModel
@inject ApplicationDbContext context

<div class="row checkoutForm">
    <img src="~/images/icon.jpg" />
    <h2>Your shopping cart</h2>
    <h4>Here are the products in your shopping cart.</h4>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Selected amount</th>
                <th>Product</th>
                <th class="text-right">Price</th>
                <th class="text-right">Subtotal</th>
               
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.ShoppingCart.ShoppingCartItems)
            {
                <tr>
                    <td class="text-center">@line.Amount</td>
                    <td class="text-left">@line.Produit.Name</td>
                    <td class="text-right">@line.Produit.AskedPrice.ToString("c")</td>
                    <td class="text-right">
                        @((line.Amount * line.Produit.AskedPrice).ToString("c"))
                    </td>
                    <td class="text-center"><a class="glyphicon glyphicon-remove text-danger remove" asp-controller="ShoppingCart" asp-action="RemoveFromShoppingCart" asp-route-produitId="@line.Produit.ProduitId">supprimer</a></td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" class="text-right  text-info">Message important:</td>
                <td class="text-right text-info">
                    <strong>Pour un achat de plus de 1000$ la livraison sera gratuite</strong>
                </td>
            </tr>
           
            <tr>
                <td colspan="3" class="text-right">Total avant taxes:</td>
                <td class="text-right">
                    @Model.shoppingCartTotal.ToString("c")
                </td>
            </tr>

            @if (Model.shoppingCartTotal >= (decimal)context.Entreprise.FirstOrDefault().LivraisonGratuite)
            {
                <tr>
                    <td colspan="3" class="text-right">Mode de livraison:</td>
                    <td class="text-right">
                        <span style="color: green">La livraison est gratuite</span>
                    </td>
                </tr>
            }

            <tr>
                <td colspan="3" class="text-right">Total apres taxes:</td>
                <td class="text-right">
                    @{
                        var tps = 1 + (decimal)context.Entreprise.FirstOrDefault().TPS;
                        var totalAv = Model.shoppingCartTotal * tps;
                        var total = totalAv.ToString("0.00$");
                    }
                    @total
                </td>
            </tr>
        </tfoot>
    </table>

    <div class="text-right">
        <div class="btn-group ">
            <a class="btn btn-success" asp-controller="Order" asp-action="Checkout">Check out</a>
            <div class="btn-group">
                <a class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    Add more product<span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li><a asp-controller="Home" asp-action="More" asp-route-id="1"> Ordinateurs </a></li>
                    <li><a asp-controller="Home" asp-action="More" asp-route-id="3"> Imprimantes </a></li>
                    <li><a asp-controller="Home" asp-action="More" asp-route-id="5"> Tabelettes </a></li>
                    <li><a asp-controller="Home" asp-action="More" asp-route-id="6"> TVs</a></li>
                    <li><a asp-controller="Home" asp-action="More" asp-route-id="2">  Meubles </a></li>
                    <li><a asp-controller="Home" asp-action="More" asp-route-id="4">Bureaux </a></li>
                </ul>
            </div>
        </div>
    </div>
</div>